// <auto-generated />
namespace HttpWebRequestHostHeader.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class New_connectionstring : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(New_connectionstring));
        
        string IMigrationMetadata.Id
        {
            get { return "202108231320221_New_connectionstring"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
